#!/system/bin/sh

# This script is supposed to be used with Another Term Lite.
# See https://github.com/green-green-avk/AnotherTermLite/wiki
# for `DATA_DIR', `LIB_DIR' and `TERMSH_UID' environment variables meaning.

inc() {
if [ -f "$1" ] ; then . "$1" ; fi
}

BASE_DIR="${0%/*}" # Old Androids could not have `dirname'.
CFG_DIR="$(readlink "$0")"
CFG_DIR="$BASE_DIR/${CFG_DIR%/*}"

export TERMSH_UID="$USER_ID" # "$(id -u)" does not work for old Androids.

export PROOT_TMP_DIR="$BASE_DIR/tmp"
export PROOT_L2S_DIR="$BASE_DIR/l2s"

mkdir -p "$PROOT_TMP_DIR"
mkdir -p "$PROOT_L2S_DIR"

# === WORKAROUND ===
PROOT_WA=('-b' "$PROOT_L2S_DIR:/var/.proot.meta")
# ===

USER=
SHELL=
PROOT_OPT_ARGS=()

inc "$CFG_DIR/run.cfg"

USER=${USER:-my_acct}
SHELL=${SHELL:-/bin/bash}
FB_SHELL='/bin/sh'
PATH='/bin:/usr/bin'
HOME="/home/$USER"
PROOT_OPT_ARGS=("${PROOT_OPT_ARGS[@]}")

if [ -n "$1" ] ; then
	UG="--change-id=$1"
	if [ "$1" = '0:0' ] ; then
		UG='-0'
		PATH='/sbin:/usr/sbin:/bin:/usr/bin'
		USER='root'
		HOME='/root'
	fi
else UG=
fi

if [ ! -x "$BASE_DIR/root/$SHELL" ] ; then SHELL="$FB_SHELL" ; fi

unset TMPDIR
unset LD_LIBRARY_PATH

export PATH
export USER
export HOME
export TERMSH=termsh # Just for convenience.

inc "$CFG_DIR/run.rc"

"$DATA_DIR/root/bin/proot" -r "$BASE_DIR/root" $UG \
-b /dev -b /proc -b /sys -b /system -b /vendor -b /storage \
-b "$LIB_DIR/libtermsh.so:/bin/termsh" \
"${PROOT_WA[@]}" \
"${PROOT_OPT_ARGS[@]}" \
--link2symlink -p -L --tcsetsf2tcsets \
-w "$HOME" "$SHELL" -l
