#!/system/bin/sh

# This script is supposed to be used with Another Term.
# See https://github.com/green-green-avk/AnotherTerm/wiki
# for `DATA_DIR', `LIB_DIR' and `TERMSH_UID' environment variables meaning.

# Arguments: [-u] [<uid>:<gid> [<command>]]
# -u -- for PRoot UserLAnd flavor from
#       https://github.com/green-green-avk/build-proot-android/tree/master/packages

inc() {
	if [ -f "$1" ] ; then . "$1" ; fi
}

TERMSH="$LIB_DIR/libtermsh.so"

BASE_DIR="${0%/*}" # Old Androids could not have `dirname'.
CFG_DIR="$(readlink "$0" 2>/dev/null || echo 'root/etc/proot/run')" # API < 19 could not have `readlink'.
CFG_DIR="$BASE_DIR/${CFG_DIR%/*}"

export TERMSH_UID="$USER_ID" # "$(id -u)" does not work for old Androids.

export PROOT_TMP_DIR="$BASE_DIR/tmp"
export PROOT_L2S_DIR="$BASE_DIR/root/.proot.meta"

mkdir -p "$PROOT_TMP_DIR"
mkdir -p "$PROOT_L2S_DIR"

USER=
SHELL=
PROOT_OPT_ARGS=()

inc "$CFG_DIR/run.cfg"

USER=${USER:-my_acct}
SHELL=${SHELL:-/bin/bash}
FB_SHELL='/bin/sh'
PATH='/bin:/usr/bin'
HOME="/home/$USER"
PROOT="${PROOT:-$DATA_DIR/root/bin/proot}"
PROOT_USERLAND="${PROOT_USERLAND:-$DATA_DIR/root/bin/proot-userland}"
PROOT_OPT_ARGS=("${PROOT_OPT_ARGS[@]}")

if [ "$1" = '-v' ]
then shift ; PROOT_OPT_ARGS+=('-v' "$1") ; shift
fi

if [ "$1" = '-u' ]
then shift ; PROOT_F="$PROOT_USERLAND"
else PROOT_F="$PROOT"
fi

if [ "$1" = '--kill-on-exit' ]
then shift ; PROOT_OPT_ARGS+=('--kill-on-exit')
fi

if [ -n "$1" ] ; then
	UG="--change-id=$1"
	if [ "$1" = '0:0' ] ; then
		UG='-0'
		PATH='/sbin:/usr/sbin:/bin:/usr/bin'
		USER='root'
		HOME='/root'
	fi
else UG=
fi

is_root() {
	[ -n "$UG" ]
}

if [ -n "$2" ]
then CMD=('-c' "$2")
else CMD=()
fi

if [ ! -x "$BASE_DIR/root/$SHELL" ] ; then SHELL="$FB_SHELL" ; fi

unset TMPDIR
unset LD_LIBRARY_PATH

export PATH
export USER
export HOME
export TERMSH=termsh # Just for convenience.

inc "$CFG_DIR/run.rc"

"$PROOT_F" -r "$BASE_DIR/root" $UG \
-b /dev -b /proc -b /sys -b /system -b /vendor -b /storage \
$([ -d /apex ] && echo -b /apex ) \
-b "$LIB_DIR/libtermsh.so:/bin/_termsh" \
"${PROOT_OPT_ARGS[@]}" \
--link2symlink -p -L --tcsetsf2tcsets \
-w "$HOME" "$SHELL" -l "${CMD[@]}"
